# Generated by Django 3.0 on 2021-12-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0004_auto_20211204_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='price',
            name='sale_amount',
            field=models.FloatField(default=0),
        ),
    ]
