# Generated by Django 3.0 on 2021-12-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0006_remove_price_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='sale_amount',
            field=models.FloatField(default=0),
        ),
    ]
