# Generated by Django 3.2.9 on 2023-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0015_purchase_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='promo_message_html',
            field=models.TextField(default=''),
        ),
    ]
