# Generated by Django 2.2.5 on 2019-09-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=30)),
                ('filename', models.CharField(default='', max_length=30)),
                ('portrait_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
