# Generated by Django 2.2.2 on 2020-08-08 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sketchyactivity.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=100)),
                ('filename', models.CharField(default='', max_length=100)),
                ('portrait_name', models.CharField(default='', max_length=100)),
                ('date', models.DateField(null=True)),
                ('s3_drawing_private_url', models.URLField(default='', max_length=500)),
                ('s3_copied_smaller_drawing_private_url', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivateOriginal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=sketchyactivity.storage_backends.PrivateMediaStorageOriginal(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivateThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=sketchyactivity.storage_backends.PrivateMediaStorageThumbnail(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
