# Generated by Django 2.2.2 on 2021-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='website_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='metastuff',
            name='website_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='metastuff',
            name='website_title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
