# Generated by Django 3.0 on 2021-12-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0005_auto_20211204_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='sale_amount',
        ),
    ]
