# Generated by Django 3.0 on 2021-12-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0007_metastuff_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='sale_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='metastuff',
            name='sale_start',
            field=models.DateField(auto_now=True),
        ),
    ]
