# Generated by Django 3.2.9 on 2022-04-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0010_auto_20220428_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_image_filename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='s3_reference_image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
