# Generated by Django 3.2.9 on 2022-05-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0011_auto_20220428_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started Yet'), ('IP', 'In Progress'), ('CMPLT', 'Complete')], default='NS', max_length=10),
        ),
    ]
