# Generated by Django 3.2.9 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0012_auto_20220502_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='profile_image_private_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
