# Generated by Django 3.2.9 on 2022-06-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0013_metastuff_profile_image_private_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='metastuff',
            name='profile_image_filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
