# Generated by Django 3.2.9 on 2022-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchyactivity', '0014_metastuff_profile_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
